### ISSUE TITLE
ConcurrentModificationException Crash

### ISSUE THREAD

**Issue by Sesu8642** [Sesu8642/FeudalTactics#65]
I received several crash reports caused by this exception:
```
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:860)
at de.sesu8642.feudaltactics.lib.gamestate.GameStateSerializer.write(GameStateSerializer.java:88)
at de.sesu8642.feudaltactics.lib.gamestate.GameStateSerializer.write(GameStateSerializer.java:18)
at com.badlogic.gdx.utils.Json.writeValue(Json.java:517)
at com.badlogic.gdx.utils.Json.toJson(Json.java:279)
at com.badlogic.gdx.utils.Json.toJson(Json.java:238)
at com.badlogic.gdx.utils.Json.toJson(Json.java:231)
at de.sesu8642.feudaltactics.ingame.AutoSaveRepository.autoSaveGameState(AutoSaveRepository.java:52)
at de.sesu8642.feudaltactics.lib.ingame.GameController.autosave(GameController.java:74)
at de.sesu8642.feudaltactics.lib.ingame.GameController.startGame(GameController.java:69)
at de.sesu8642.feudaltactics.ingame.LocalIngameInputHandler.handleGameStart(LocalIngameInputHandler.java:232)
at java.lang.reflect.Method.invoke(Native Method)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0$com-google-common-eventbus-Subscriber(Subscriber.java:71)
at com.google.common.eventbus.Subscriber$$ExternalSyntheticLambda0.run(Unknown Source:4)
at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:109)
at [com.google.common.eventbus.EventBus.post](http://com.google.common.eventbus.eventbus.post/)(EventBus.java:267)
at de.sesu8642.feudaltactics.ingame.ui.IngameScreen.lambda$addParameterInputListeners$15$de-sesu8642-feudaltactics-ingame-ui-IngameScreen(IngameScreen.java:470)
at de.sesu8642.feudaltactics.ingame.ui.IngameScreen$$ExternalSyntheticLambda5.run(Unknown Source:2)
at de.sesu8642.feudaltactics.menu.common.ui.ExceptionLoggingChangeListener.handle(ExceptionLoggingChangeListener.java:32)
at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
at com.badlogic.gdx.backends.android.DefaultAndroidInput.processEvents(DefaultAndroidInput.java:426)
at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:472)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

It seems to be happening during the but turn after the game starts. Relevant log line:
```
[2023-09-17 15:48:25.561] [SEVERE] com.google.common.eventbus.SubscriberExceptionHandler an unexpected error happened while handling the event de.sesu8642.feudaltactics.events.moves.GameStartEvent@c2dfb17 in method public void de.sesu8642.feudaltactics.ingame.LocalIngameInputHandler.handleGameStart(de.sesu8642.feudaltactics.events.moves.GameStartEvent) of subscriber de.sesu8642.feudaltactics.ingame.LocalIngameInputHandler@e2fd8e3
```

**Comment by Sesu8642** [comment]
AutoSaveRepository#autoSaveGameState is sometimes called by the main thread and sometimes by the BotAi one. One reporter mentioned that the crash happened when starting a new game after the previous one ended. It could be that the AI thread from the old game was still running an autosaving.

**Comment by Sesu8642** [comment]
Found a report where it seemingly happened in the first game played after the app was started.

**Comment by Sesu8642** [comment]
All the detailed reports that I have have the "show enemy turns" option disabled.

**Comment by Sesu8642** [comment]
Think I found the problem. GameController#startGame will start the AI thread to do its turn and afterwards trigger an autosave. If the AI turn is very fast, it will trigger an autosave at the same time the first one it still running.
