### ISSUE TITLE
Running FeudalTactics on Mobile Linux

### ISSUE THREAD

**Issue by jonnius** [Sesu8642/FeudalTactics#84]
I tried starting the release desktop jar like `java -jar FeudalTactics-desktop.jar` on an arm64 Ubuntu Touch Linux device, but keep getting:

```
[LWJGL] GLFW_API_UNAVAILABLE error
        Description : EGL: Failed to find support for OpenGL
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
                de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:24)
                de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:16)
[de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher] the game crashed because of an unexpected exception
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:530)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
        at de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:24)
        at de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:16)
```

I assume, it is requiring OpenGL support, while Ubuntu Touch provides GLES. As you support Android, I assume that GLES should be supported by this game. Is that correct? Can you provide any guidance how to package/start the game so that it utilizes GLES?

**Comment by Sesu8642** [comment]
I think you might need to edit the config in de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher. See https://libgdx.com/wiki/graphics/opengl-es-support.

**Comment by Sesu8642** [comment]
Any update on this?

**Comment by jonnius** [comment]
Thanks for your suggestion and sorry for not getting back on this, yet. I didn't find the time time yet to try it out. I will report once there is news.

**Comment by jonnius** [comment]
I finally got to test again. I found that configuring the OpenGL emulation as suggested doesn't change anything, even though I don't know which version my FP4 with UT actually supports. What I found though is that I only get that error when starting the app from an SSH session, not starting it from the device itself. There it actually starts.

I still have issues, namely that some areas are not clickable (`de.sesu8642.feudaltactics.lib.ingame.GameController clicked: null`) and that it doesn't seem to support Wayland (only runs through XWayland). Should I close this one and open separate issues for these?

**Comment by Sesu8642** [comment]
The log line you quote is the expected output if you click water. If you didn't, please open a separate issue.
Wayland support must be implemented in the LibGDX framework which in turn uses LWJGL3. It's out of scope for me but feel free to open an issue there.

**Comment by jonnius** [comment]
Will open one for the missing clicks after some more testing...

Which version of lwjgl/glfw does this project use? Looking at [https://github.com/libgdx/libgdx/issues/7495](this issue), it seems that starting with LWJGL 3.3.4 /  GLFW 3.4 it would run natively on Wayland.

**Comment by Sesu8642** [comment]
Its using 3.3.3. libGDX downgraded it after there were some antivirus detection problems. See https://github.com/LWJGL/lwjgl3/issues/1005
It seems to be fixed in 3.3.6 but the latest libGDX still uses 3.3.3. I will upgrade after libGDX does so.

**Comment by jonnius** [comment]
Where can I see/configure the versions for testing?

**Comment by jonnius** [comment]
Just for reference, I pushed my packaging test configuration here: https://github.com/jonnius/FeudalTactics/tree/ut

**Comment by jonnius** [comment]
I added the following in lwjgl3/build.gradle:
```
configurations.all {
    resolutionStrategy {
        force("org.lwjgl:lwjgl-glfw:3.3.6")
    }
}
```

This leads to
```syslog
Apr 27 17:19:31 ubuntu-phablet aa-exec[50165]: [LWJGL] Failed to load a library. Possible solutions:
Apr 27 17:19:31 ubuntu-phablet aa-exec[50165]:         a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
Apr 27 17:19:31 ubuntu-phablet aa-exec[50165]:         b) Add the JAR that contains the shared library to the classpath.
Apr 27 17:19:31 ubuntu-phablet aa-exec[50165]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
Apr 27 17:19:31 ubuntu-phablet aa-exec[50165]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Apr 27 17:19:31 ubuntu-phablet aa-exec[50165]: Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so
```

**Comment by Sesu8642** [comment]
Probably upgrading takes more than just pulling the new version.
Another option is to set gdxVersion=1.13.0 in gradle.properties. It does start and actually gives me some Wayland error messages in the background.

**Comment by jonnius** [comment]
Unfortunately, that leads to the same result of the missing liblwjgl.so. :(

**Comment by Sesu8642** [comment]
Does your jar run on x86 Linux? I checked the contents and the .so file for arm64 seems to be present. It might be a bug in libGDX.

**Comment by jonnius** [comment]
Yes, it does run on x86, but not on arm64. Should I make a bug report at libGDX?

**Comment by Sesu8642** [comment]
First lets make sure the issue is not related to Feudal Tactics. Can you please try running a dummy project generated with the latest [gdx-liftoff](https://github.com/libgdx/gdx-liftoff/releases)?
You can select the libGDX version to use for the generated project. I think both 1.13.0 (lwjgl 3.3.4) and 1.13.1 (lwjgl 3.3.3) are relevant for testing.
Let me know if you need help.

**Comment by jonnius** [comment]
I tried, but unfortunately, the liftoff seems to generate a broken build config:

```
$ ./gradlew lwjgl:dist
[...]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/jonatan/dev/DummyGdx/lwjgl3/build.gradle' line: 52

* What went wrong:
Could not compile build file '/home/jonatan/dev/DummyGdx/lwjgl3/build.gradle'.
> startup failed:
  build file '/home/jonatan/dev/DummyGdx/lwjgl3/build.gradle': 52: Unexpected input: '{' @ line 52, column 5.
     jar {
         ^
  
  1 error
```

**Comment by jonnius** [comment]
I tried again a dummy project with libGDX 1.14.2. With this I am back to initial `GLFW_API_UNAVAILABLE` error, not only when starting it via SSH...

Anyways, I also tried the newest Release of Feudal Tactics. And there it gets interesting. On one phone running Ubuntu Touch 24.04-2.x, it does not start and the log looks like it tries to use Vulkan intead of OpenGL which does not seem to be supported. It fails with:
```
Jun 05 10:25:53 ubuntu-phablet aa-exec[42176]: dlopen failed: library "vulkan.adreno.so" not found
Jun 05 10:25:53 ubuntu-phablet aa-exec[42176]: dlopen failed: library "vulkan.lahaina.so" not found
Jun 05 10:25:53 ubuntu-phablet aa-exec[42176]: invalid stub function called
```

On my other phone running Ubuntu Touch 24.04-1.x, it actually starts and kind of works as expected. I was able to play. Except that the scaling is messed up. Controls are huge and therefore does not fit on the screen. And in-game I can't zoom in. It looks like this:

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/06c619ed-f6c3-4cb1-b6e7-954df17dab0a" />

The first two lines of the log look like they may be relevant:

```
Jun 05 11:12:22 ubuntu-phablet aa-exec[97271]: MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
Jun 05 11:12:22 ubuntu-phablet aa-exec[97271]: glx: failed to create drisw screen
```

**Comment by Sesu8642** [comment]
Thanks for reporting back!

> Except that the scaling is messed up.

I added dynamic scaling in 1.5. If the screen width is < 15 cm and the game is full screen, I assume a handheld device. In that case, the smaller scaling is applied. Ubuntu might be mis-reporting (or not reporting at all) something here. I should add a log message about that. You could try Feudal Tactics 1.4 and see if the scaling is better. I did not change the LibGDX version since.

> And in-game I can't zoom in.

I suspect LibGDX doesn't support gestures on Linux.

It looks like the rendering of semi-transparency is also messed up on your device (shallow water).

**Comment by jonnius** [comment]
> > Except that the scaling is messed up.
> 
> I added dynamic scaling in 1.5. If the screen width is < 15 cm and the game is full screen, I assume a handheld device. In that case, the smaller scaling is applied. Ubuntu might be mis-reporting (or not reporting at all) something here. I should add a log message about that. You could try Feudal Tactics 1.4 and see if the scaling is better. I did not change the LibGDX version since.

With 1.4 the scaling is correct. Small maps are well playable, only big maps suffer from the lack of zooming... If I find enough time, I might try to debug the screen width issue. Another workaround could be to allow disabling this feature, e.g. via a command line parameter. 
> > And in-game I can't zoom in.
> 
> I suspect LibGDX doesn't support gestures on Linux.

Let's see if I find time investigating this. A workaround here could be optional zoom buttons that could be enabled via command line parameters.
> It looks like the rendering of semi-transparency is also messed up on your device (shallow water).

That seems to be an issue with the screenshot only. On the screen it looks correct.
