### ISSUE TITLE
build instructions from wiki fail

### ISSUE THREAD

**Issue by doniks** [Sesu8642/FeudalTactics#94]
I'm following the steps from here: https://github.com/Sesu8642/FeudalTactics/wiki/Building-the-Project but this fails ... seemingly no java compiler found?! It's been too long since I touched java last. Do you know what's at hand?

```
./gradlew lwjgl:run
Downloading https://services.gradle.org/distributions/gradle-8.10.1-bin.zip
.............10%.............20%.............30%.............40%.............50%.............60%.............70%.............80%.............90%.............100%

Welcome to Gradle 8.10.1!

Here are the highlights of this release:
 - Support for Java 23
 - Faster configuration cache
 - Better configuration cache reports

For more details see https://docs.gradle.org/8.10.1/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 
> Task :core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':core:compileJava'.
   > Failed to calculate the value of task ':core:compileJava' property 'javaCompiler'.
      > Toolchain installation '/usr/lib/jvm/java-21-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1m 16s
1 actionable task: 1 executed


./gradlew lwjgl:run
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 
> Task :core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':core:compileJava'.
   > Failed to calculate the value of task ':core:compileJava' property 'javaCompiler'.
      > Toolchain installation '/usr/lib/jvm/java-21-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 6s
1 actionable task: 1 executed


./gradlew lwjgl:dist
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 
> Task :core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Error while evaluating property 'javaCompiler' of task ':core:compileJava'.
   > Failed to calculate the value of task ':core:compileJava' property 'javaCompiler'.
      > Toolchain installation '/usr/lib/jvm/java-21-openjdk-amd64' does not provide the required capabilities: [JAVA_COMPILER]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 6s
1 actionable task: 1 executed
```

**Comment by Sesu8642** [comment]
Gradle is using Java 21 while the instructions mention to install Java 17. Java 21 might be a JRE you have installed, which is not sufficient (JDK is required).
You can run this to override the setting:
```
./gradlew lwjgl:run -Dorg.gradle.java.home=/path_to_jdk_directory
```
See https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version for some other ways.

**Comment by doniks** [comment]
ah. yes with 21 it works. I've uninstalled v17 again and then `sudo apt install openjdk-21-jdk`. Afterwards it worked. Maybe the wiki page needs updating

**Comment by doniks** [comment]
PS: the first run actually crashed. Second one worked fine.


```
./gradlew lwjgl:run
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 

> Task :core:compileJava
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

> Task :lwjgl3:compileJava
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

> Task :lwjgl3:run
[2025-01-02 15:21:21.978] [INFO] de.sesu8642.feudaltactics.lib.ingame.GameController loading latest autosave 
[2025-01-02 15:21:22.063] [SEVERE] com.google.common.eventbus.SubscriberExceptionHandler an unexpected error happened while handling the event de.sesu8642.feudaltactics.events.GameResumedEvent@4a3631f8 in method public void de.sesu8642.feudaltactics.lib.ingame.GameControllerEventHandler.handleGameResumed(de.sesu8642.feudaltactics.events.GameResumedEvent) of subscriber de.sesu8642.feudaltactics.lib.ingame.GameControllerEventHandler@7b50df34 
[2025-01-02 15:21:22.085] [SEVERE] com.google.common.eventbus.SubscriberExceptionHandler an unexpected error happened while handling the event de.sesu8642.feudaltactics.events.CenterMapEvent@4f74980d in method public void de.sesu8642.feudaltactics.ingame.IngameRendererEventHandler.handleMapCentering(de.sesu8642.feudaltactics.events.CenterMapEvent) of subscriber de.sesu8642.feudaltactics.ingame.IngameRendererEventHandler@6f8e8894 
[de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher] the game crashed because of an unexpected exception
de.sesu8642.feudaltactics.exceptions.FatalErrorException: java.lang.NullPointerException: Cannot invoke "de.sesu8642.feudaltactics.lib.gamestate.GameState.getMap()" because "gameState" is null
        at de.sesu8642.feudaltactics.menu.crashreporting.ui.CrashingScreen.render(CrashingScreen.java:23)
        at com.badlogic.gdx.Game.render(Game.java:48)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
        at de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:24)
        at de.sesu8642.feudaltactics.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:16)
Caused by: java.lang.NullPointerException: Cannot invoke "de.sesu8642.feudaltactics.lib.gamestate.GameState.getMap()" because "gameState" is null
        at de.sesu8642.feudaltactics.renderer.MapRenderer.placeCameraForFullMapView(MapRenderer.java:624)
        at de.sesu8642.feudaltactics.ingame.IngameRendererEventHandler.handleMapCentering(IngameRendererEventHandler.java:46)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
        at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
        at com.google.common.eventbus.EventBus.post(EventBus.java:270)
        at de.sesu8642.feudaltactics.GameInitializer.initializeGame(GameInitializer.java:87)
        at de.sesu8642.feudaltactics.FeudalTactics.create(FeudalTactics.java:23)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
        ... 4 more
[2025-01-02 15:21:22.105] [FINE] java.lang.Runtime Runtime.exit() called with status: 1 

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 21s
6 actionable tasks: 6 executed

./gradlew lwjgl:run
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build 

> Task :core:compileJava
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

> Task :lwjgl3:run
[2025-01-02 15:22:26.278] [INFO] de.sesu8642.feudaltactics.lib.ingame.GameController generating a new game state with bot intelligence LEVEL_4 and MapParameters [players=[Player [playerIndex=0, type=LOCAL_PLAYER, defeated=false], Player [playerIndex=1, type=LOCAL_BOT, defeated=false], Player [playerIndex=2, type=LOCAL_BOT, defeated=false], Player [playerIndex=3, type=LOCAL_BOT, defeated=false], Player [playerIndex=4, type=LOCAL_BOT, defeated=false], Player [playerIndex=5, type=LOCAL_BOT, defeated=false]], seed=1735827746276, landMass=1000, density=3.0] 
[2025-01-02 15:22:32.006] [INFO] de.sesu8642.feudaltactics.lib.ingame.GameController starting game 
[2025-01-02 15:22:32.007] [FINE] de.sesu8642.feudaltactics.ingame.AutoSaveRepository autosaving full gamestate 
[2025-01-02 15:22:32.062] [FINE] de.sesu8642.feudaltactics.lib.ingame.botai.BotAi doing the turn for bot player 'Player [playerIndex=5, type=LOCAL_BOT, defeated=false]' with intelligence level 'LEVEL_4' 
[2025-01-02 15:22:32.064] [FINE] de.sesu8642.feudaltactics.lib.ingame.botai.BotAi doing moves in kingdom 'Kingdom [tiles=java.util.stream.ReferencePipeline$3@d95d19f, player=Player [playerIndex=5, type=LOCAL_BOT, defeated=false], savings=15, doneMoving=true, wasActiveInCurrentTurn=false]' 
[2025-01-02 15:22:32.064] [FINE] de.sesu8642.feudaltactics.lib.ingame.botai.BotAi picking up all available units 
[2025-01-02 15:22:32.065] [FINE] de.sesu8642.feudaltactics.lib.ingame.botai.BotAi removing blocking objects 
```

**Comment by Sesu8642** [comment]
I updated the instructions and added instructions on how to set the default JDK.
I have seen the exception before but don't know how to reproduce it. Let me know if you find out.
